baseURL = "https://getporter.org/"
languageCode = "en-us"
title = "Porter"
canonifyURLs = "false"
relativeURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[module]
[[module.imports]]
    path = 'github.com/imfing/hextra'

# Syntax Highlighting
pygmentsUseClasses = true
pygmentsStyle = "friendly"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

  [markup.highlight]
    noClasses= false

# Default Page Parameters
[params]
  title = "Porter"
  author = "Carolyn Van Slyck"
  description = "A Friendly Cloud Installer for Cloud Native Application Bundles"
  image = "images/porter-twitter-card.png"

  [params.navbar.logo]
    path = "images/porter-icon-badge.png"

#
# Docs Navigation
#

[[menu.main]]
name = "Install"
url = "/docs/getting-started/install-porter"
identifier = "install-porter"
weight = 1

[[menu.main]]
name = "QuickStart"
url = "/docs/quickstart"
identifier = "quickstart"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
identifier = "blog"
weight = 3

[[menu.main]]
name = "Community"
url = "/community"
identifier = "community"
weight = 4

[[menu.main]]
name = "Learning"
url = "/docs/learn"
identifier = "learn"
weight = 5

[[menu.main]]
name = "Docs"
url = "/docs"
identifier = "docs"
weight = 6

[[menu.main]]
name = "Search"
weight = 7
  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 8
url = "https://github.com/getporter/porter"
  [menu.main.params]
  icon = "github"


# sidebar


# # Introduction
# [[menu.sidebar]]
#   name = "Introduction"
#   identifier = "introduction"
#   url = "/docs/introduction"
#
#   [[menu.sidebar]]
#     name = "What is Porter?"
#     url = "/docs/introduction/what-is-porter"
#     identifier = "what-is-porter"
#
#   [[menu.sidebar]]
#     name = "Concepts and Components"
#     url = "/docs/introduction/concepts-and-components"
#     identifier = "concepts-and-components"
#
#     [[menu.sidebar]]
#     name = "Bundles"
#     identifier = "intro-bundles"
#     url = "/docs/introduction/intro-bundles"
#
#     [[menu.sidebar]]
#     name = "Parameters"
#     identifier = "intro-parameters"
#     url = "/docs/introduction/intro-parameters"
#
#     [[menu.sidebar]]
#     name = "Credentials"
#     identifier = "intro-credentials"
#     url = "/docs/introduction/intro-credentials"
#
#     [[menu.sidebar]]
#     name = "Configuration"
#     identifier = "intro-configuration"
#     url = "/docs/introduction/intro-configuration"
#
#     [[menu.sidebar]]
#     name = "Desired State"
#     identifier = "intro-desired-state"
#     url = "/docs/introduction/intro-desired-state"
#
#     [[menu.sidebar]]
#     name = "Invocation Images"
#     identifier = "intro-invocation-images"
#     url = "/docs/introduction/intro-invocation-images"
#
#     [[menu.sidebar]]
#     name = "Mixins"
#     identifier = "intro-mixins"
#     url = "/docs/introduction/intro-mixins"
#
#     [[menu.sidebar]]
#     name = "Plugins"
#     identifier = "intro-plugins"
#     url = "/docs/introduction/intro-plugins"
#
#     [[menu.sidebar]]
#     name = "Mixins vs Plugins"
#     identifier = "mixins-vs-plugins"
#     url = "/docs/introduction/mixins-vs-plugins"
#
# # QuickStart
# [[menu.sidebar]]
#   name = "QuickStart"
#   url = "/docs/quickstart"
#   identifier = "quickstart"
# # Getting Started
# [[menu.sidebar]]
#   name = "Getting Started"
#   url = "/docs/getting-started"
#   identifier = "getting-started"
#   [[menu.sidebar]]
#     name = "Install Porter"
#     url = "/docs/getting-started/install-porter"
#     identifier = "install-porter"
#     parent = "getting-started"
#   [[menu.sidebar]]
#     name = "Migrate Porter v0 to v1"
#     url = "/docs/getting-started/migrate-v0-v1"
#     identifier = "migrate-v0-v1"
#     parent = "getting-started"
#   [[menu.sidebar]]
#   name = "Create a Bundle"
#   url = "/docs/getting-started/create-bundle"
#   identifier = "create-bundle"
#   parent = "getting-started"
#
# # Configuration
# [[menu.sidebar]]
#   name = "Configuration"
#   url = "/configuration/configuration"
#   identifier = "configuration"
# # Operations
# [[menu.sidebar]]
#   name = "Operations"
#   url = "/operations"
#   identifier = "operations"
#   [[menu.sidebar]]
#   name = "Manage Installations"
#   url = "/operations/manage-installations"
#   identifier = "manage-installations"
#   parent = "operations"
#   [[menu.sidebar]]
#   name = "Examine Bundles"
#   url = "/operations/examine-bundles"
#   identifier = "examine-bundles"
#   parent = "operations"
#   [[menu.sidebar]]
#   name = "View Logs"
#   url = "/operations/view-logs"
#   identifier = "view-logs"
#   parent = "operations"
#   [[menu.sidebar]]
#   name = "Create a Porter Config File"
#   url = "/operations/create-porter-config"
#   identifier = "create-porter-config"
#   parent = "operations"
#   [[menu.sidebar]]
#   name = "Connect to Docker"
#   url = "/operations/connect-to-docker"
#   identifier = "connect-to-docker"
#   parent = "operations"
#   [[menu.sidebar]]
#   name = "Connect to Registry"
#   url = "/operations/connect-to-registry"
#   identifier = "connect-to-registry"
#   weight = 25
#   parent = "operations"
# # Administration
# [[menu.sidebar]]
#   name = "Administration"
#   url = "#"
#   identifier = "administration"
#   weight = 25
#   [[menu.sidebar]]
#   name = "Inspecting Bundles"
#   url = "/administration/inspecting-bundles"
#   identifier = "inspecting-bundles"
#   weight = 1
#   parent = "administration"
#   [[menu.sidebar]]
#   name = "Copy Bundles"
#   url = "/administration/copy-bundles"
#   identifier = "copy-bundles"
#   weight = 5
#   parent = "administration"
#   [[menu.sidebar]]
#   name = "Move Bundles Across Airgapped Environments"
#   url = "/administration/move-bundles-airgapped"
#   identifier = "move-bundles-airgapped"
#   weight = 10
#   parent = "administration"
#   [[menu.sidebar]]
#   name = "Collect Diagnostics from Porter"
#   url = "/administration/collect-diag-porter"
#   identifier = "collect-diag-porter"
#   weight = 15
#   parent = "administration"
# # Development
# [[menu.sidebar]]
#   name = "Development"
#   url = "#"
#   identifier = "development"
#   weight = 30
#   [[menu.sidebar]]
#   name = "Authoring a Bundle"
#   url = "#"
#   identifier = "author-a-bundle"
#   parent = "development"
#   weight = 1
#     [[menu.sidebar]]
#     name = "Create a Bundle"
#     url = "/development/create-a-bundle"
#     identifier = "create-a-bundle"
#     weight = 1
#     parent = "author-a-bundle"
#     [[menu.sidebar]]
#     name = "Using a Custom Dockerfile"
#     url = "/development/use-custom-dockerfile"
#     identifier = "use-custom-dockerfile"
#     weight = 5
#     parent = "author-a-bundle"
#     [[menu.sidebar]]
#     name = "Working with Dependencies"
#     url = "/development/working-with-dependencies"
#     identifier = "working-with-dependencies"
#     weight = 10
#     parent = "author-a-bundle"
#     [[menu.sidebar]]
#     name = "Using Templates"
#     url = "/development/using-templates"
#     identifier = "using-templates"
#     weight = 15
#     parent = "author-a-bundle"
#     [[menu.sidebar]]
#     name = "Distributing a Bundle"
#     url = "/development/distribute-bundles"
#     identifier = "distribute-bundles"
#     weight = 20
#     parent = "author-a-bundle"
#   [[menu.sidebar]]
#   name = "Developing a Mixin"
#   url = "/development/dev-a-mixin"
#   identifier = "dev-a-mixin"
#   parent = "development"
#   weight = 5
#   [[menu.sidebar]]
#   name = "Distributing a Mixin"
#   url = "/development/dist-a-mixin"
#   identifier = "dist-a-mixin"
#   parent = "development"
#   weight = 10
# # How-To Guides
# [[menu.sidebar]]
#   name = "How-To Guides"
#   url = "#"
#   identifier = "how-to-guides"
#   weight = 35
#   [[menu.sidebar]]
#   name = "Working with Mixins"
#   url = "/how-to-guides/work-with-mixins"
#   identifier = "work-with-mixins"
#   parent = "how-to-guides"
#   weight = 1
#   [[menu.sidebar]]
#   name = "Working with Plugins"
#   url = "/how-to-guides/work-with-plugins"
#   identifier = "work-with-plugins"
#   parent = "how-to-guides"
#   weight = 5
# # Porter Operator
# [[menu.sidebar]]
# name = "Porter Operator"
# identifier = "porter-operator"
# weight = 40
#   [[menu.sidebar]]
#   name = "Overview"
#   identifier = "operator-overview"
#   url = "/operator/"
#   weight = 1
#   parent = "porter-operator"
#   [[menu.sidebar]]
#   name = "QuickStart"
#   identifier = "operator-quickstart"
#   url = "/docs/operator/quickstart/"
#   weight = 5
#   parent = "porter-operator"
#   [[menu.sidebar]]
#   name = "Install"
#   identifier = "operator-install"
#   url = "/operator/install/"
#   weight = 10
#   parent = "porter-operator"
#   [[menu.sidebar]]
#   name = "File Formats"
#   identifier = "operator-file-formats"
#   url = "/operator/file-formats/"
#   weight = 15
#   parent = "porter-operator"
# # Troubleshooting
# [[menu.sidebar]]
#   name = "Troubleshooting"
#   url = "/troubleshooting/troubleshooting"
#   identifier = "troubleshooting"
#   weight = 45
# # Best Practices
# [[menu.sidebar]]
#   name = "Best Practices"
#   url = "#"
#   identifier = "best-practices"
#   weight = 50
#   [[menu.sidebar]]
#   name = "When to use Credentials vs Parameters"
#   url = "/best-practices/credentials-or-parameters"
#   identifier = "credentials-or-parameters"
#   parent = "best-practices"
#   weight = 1
#   [[menu.sidebar]]
#   name = "Best Practices for the exec mixin"
#   url = "/best-practices/exec-mixin"
#   identifier = "exec-mixin"
#   parent = "best-practices"
#   weight = 5
#   [[menu.sidebar]]
#   name = "Best Practices for Porter in a CI Pipeline"
#   url = "/best-practices/ci-pipeline"
#   identifier = "ci-pipeline"
#   parent = "best-practices"
#   weight = 10
# # Integrations
# [[menu.sidebar]]
#   name = "Integrations"
#   url = "#"
#   identifier = "integrations"
#   weight = 50
#   [[menu.sidebar]]
#   name = "Connect to AKS Cluster"
#   url = "/integrations/aks"
#   identifier = "aks"
#   parent = "integrations"
#   weight = 1
#   [[menu.sidebar]]
#   name = "Connect to GKE Cluster"
#   url = "/integrations/gke"
#   identifier = "gke"
#   parent = "integrations"
#   weight = 5
#   [[menu.sidebar]]
#   name = "Connect to KinD Cluster"
#   url = "/integrations/kind"
#   identifier = "kind"
#   parent = "integrations"
#   weight = 10
#   [[menu.sidebar]]
#   name = "Connect to Minikube Cluster"
#   url = "/integrations/minikube"
#   identifier = "minikube"
#   parent = "integrations"
#   weight = 15
# # Learn Porter
# [[menu.sidebar]]
#   name = "Learn Porter"
#   url = "/learn/learning"
#   identifier = "learn-porter"
#   weight = 55
# # Contribute
# [[menu.sidebar]]
#   name = "Contribute"
#   url = "#"
#   identifier = "contribute"
#   weight = 60
#   [[menu.sidebar]]
#   name = "How to Contribute"
#   url = "/contribute/"
#   identifier = "contribute-how"
#   parent = "contribute"
#   weight = 1
#   [[menu.sidebar]]
#   name = "Contributing Tutorial"
#   url = "/contribute/tutorial"
#   identifier = "contribute-tutorial"
#   parent = "contribute"
#   weight = 5
#   [[menu.sidebar]]
#   name = "Contributing Guide"
#   url = "/contribute/guide"
#   identifier = "contribute-guide"
#   parent = "contribute"
#   weight = 10
#   [[menu.sidebar]]
#   name = "Make a Proposal"
#   url = "/contribute/proposals"
#   identifier = "contribute-proposals"
#   parent = "contribute"
#   weight = 15
# # References
# [[menu.sidebar]]
#   name = "References"
#   url = "#"
#   identifier = "references"
#   weight = 60
#   [[menu.sidebar]]
#   name = "CNAB Specification"
#   url = "https://cnab.io/"
#   identifier = "cnab-spec"
#   weight = 1
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Porter Commands"
#   url = "#"
#   identifier = "cli"
#   weight = 5
#   parent = "references"
#   [[menu.sidebar]]
#     name = "Overview"
#     url = "/references/cli/porter"
#     identifier = "cli-overview"
#     weight = 1
#     parent = "cli"
#   [[menu.sidebar]]
#     name = "Bundles"
#     url = "/references/cli/bundles"
#     identifier = "cli-bundles"
#     weight = 5
#     parent = "cli"
#   [[menu.sidebar]]
#     name = "Credentials"
#     url = "/references/cli/credentials"
#     identifier = "cli-credentials"
#     weight = 10
#     parent = "cli"
#   [[menu.sidebar]]
#     name = "Parameters"
#     url = "/references/cli/parameters"
#     identifier = "cli-parameters"
#     weight = 15
#     parent = "cli"
#   [[menu.sidebar]]
#     name = "Installations"
#     url = "/references/cli/installations"
#     identifier = "cli-installations"
#     weight = 20
#     parent = "cli"
#   [[menu.sidebar]]
#     name = "Mixins"
#     url = "/references/cli/mixins"
#     identifier = "cli-mixins"
#     weight = 25
#     parent = "cli"
#   [[menu.sidebar]]
#     name = "Plugins"
#     url = "/references/cli/plugins"
#     identifier = "cli-plugins"
#     weight = 30
#     parent = "cli"
#   [[menu.sidebar]]
#   name = "Compatible Registries"
#   url = "/references/compatible-registries"
#   identifier = "compat-registries"
#   weight = 10
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Docker Images"
#   url = "/references/docker-images/"
#   identifier = "docker-images"
#   weight = 15
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Examples"
#   url = "/references/examples/"
#   identifier = "examples"
#   weight = 20
#   parent = "references"
#   [[menu.sidebar]]
#   name = "File Formats"
#   url = "/references/file-formats/"
#   identifier = "file-formats"
#   weight = 25
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Logos"
#   url = "/references/logo/"
#   identifier = "logo"
#   weight = 30
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Porter Go Library"
#   url = "/references/library/"
#   identifier = "library"
#   weight = 35
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Porter Lint Messages"
#   url = "/references/linter"
#   identifier = "linter"
#   weight = 40
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Project Short Links"
#   url = "/references/short-links"
#   identifier = "short-links"
#   weight = 45
#   parent = "references"
#   [[menu.sidebar]]
#   name = "Version Strategy"
#   url = "/references/version-strategy"
#   identifier = "version-strategy"
#   weight = 50
#   parent = "references"
# # FAQ
# [[menu.sidebar]]
#   name = "FAQ"
#   url = "/faq/faq"
#   identifier = "faq"
#   weight = 65
#
